#include "pch.h"
#include "Mapper.h"

#include <unordered_map>

static std::unordered_map<std::string_view, std::string_view> g_Mappings;
void Mapper::Initialize(const GameVersions version)
{
	switch (version)
	{
	case CASUAL_1_7_10: {
		g_Mappings = {
			{"net/minecraft/client/Minecraft", "bao"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "bjk"},
			{"net/minecraft/client/multiplayer/WorldClient", "bjf"},
			{"net/minecraft/client/gui/GuiScreen", "bdw"},
			{"net/minecraft/client/renderer/entity/RenderManager", "bnn"},
			{ "net/minecraft/entity/Entity", "sa" },
			{"net/minecraft/client/renderer/entity/Render", "bno"},
			{"net/minecraft/client/model/ModelBase", "bhr"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "baj"},
			{ "net/minecraft/util/IChatComponent", "fj" },
			{"net/minecraft/client/model/ModelRenderer", "bix"},
			{"net/minecraft/util/Timer", "bbr"},
			{"net/minecraft/client/gui/Gui", "bbw"},
			{"net/minecraft/client/gui/FontRenderer", "bbu"},
			{ "net/minecraft/util/AxisAlignedBB", "azt" },
			{"net/minecraft/client/gui/GuiChat", "bct"},
			{"net/minecraft/client/renderer/entity/RendererLivingEntity", "boh"},
			{ "net/minecraft/item/ItemStack", "add" },
			{ "net/minecraft/item/ItemSword", "aeh" },
			{ "net/minecraft/item/ItemAxe", "abf" },
			{ "net/minecraft/item/Item", "adb" },
			{ "net/minecraft/item/ItemBlock", "abh" },
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "azv"},
			{"net/minecraft/util/MovingObjectPosition", "azu"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "bfu"},
			{"net/minecraft/client/gui/GuiChat", "bct"},
			{"net/minecraft/entity/player/InventoryPlayer", "yx"},
			{"net/minecraft/item/ItemEnderPearl", "aco"},
			{ "net/minecraft/block/Block", "aji" },
			{"net/minecraft/client/settings/GameSettings", "bbj"},
			{ "net/minecraft/client/settings/KeyBinding", "bal" },
			{"net/minecraft/block/BlockAir", "aja"},
			{ "keyBindSneak", "Z" },
			{ "pressed", "h" },
			{"gameSettings", "u"},
			{ "getBlock", "a" },
			{ "getIdFromBlock", "b" },
			{"theMinecraft", "M"},
			{"thePlayer", "h"},
			{"theWorld", "f"},
			{"currentScreen", "n"},
			{"renderManagerInstance", "a"},
			{"getEntityRenderObject", "a"},
			{"mainModel", "i"},
			{"PROJECTION", "k"},
			{"MODELVIEW", "j"},
			{"playerEntities", "h"},
			{ "getDisplayName", "c_" },
			{ "getUnformattedTextForChat", "e" },
			{"rotationPitch", "z"},
			{"rotationYaw", "y"},
			{"prevRotationYaw", "A"},
			{"prevRotationPitch", "B"},
			{"posX", "s"},
			{"posY", "t"},
			{"posZ", "u"},
			{"motionX", "v"},
			{"motionY", "w"},
			{"motionZ", "x"},
			{"maxHurtResistantTime", "aH"},
			{"hurtResistantTime", "ad"},
			{"bipedHeadwear", "d"},
			{"bipedRightArm", "f"},
			{"bipedLeftArm", "g"},
			{"bipedRightLeg", "h"},
			{"bipedLeftLeg", "i"},
			{"rotateAngleX","f"},
			{"rotateAngleY","g"},
			{"rotateAngleZ","h"},
			{"prevRenderYawOffset", "aN"},
			{"renderYawOffset", "aM"},
			{ "renderPartialTicks", "c" },
			{ "lastTickPosX", "S" },
			{ "lastTickPosY", "T" },
			{ "lastTickPosZ", "U" },
			{"timer", "Q"},
			{ "displayWidth", "d" },
			{ "displayHeight", "e" },
			{"renderPosX", "b"},
			{"renderPosY", "c"},
			{"renderPosZ", "d"},
			{"drawRect", "a"},
			{"getStringWidth", "a"},
			{"drawString", "a"},
			{"fontRendererObj", "l"},
			{ "getHealth", "aS" },
			{"setAlwaysRenderNameTag",  "g"},
			{ "isInvisible", "ap" },
			{"maxHurtResistantTime", "aH"},
			{"hurtResistantTime", "ad"},
			{"viewerPosX", "m"},
			{"viewerPosY", "n" },
			{"viewerPosZ", "o" },
			{ "boundingBox", "C" },
			{"minX", "a"},
			{"minY", "b"},
			{"minZ", "c"},
			{"maxX", "d"},
			{"maxY", "e"},
			{"maxZ", "f"},
			{ "prevPosX", "p" },
			{ "prevPosY", "q" },
			{ "prevPosZ", "r" },
			{"isSneaking", "an"},
			{"rotationYawHead", "aO"},
			{"onGround", "D"},
			{ "getHeldItem", "be" },
			{"item", "e"},
			{ "getItem", "b" },
			{"typeOfHit", "a"},
			{"BLOCK", "b"},
			{"ENTITY", "c"},
			{ "objectMouseOver", "t" },
			{"inWater", "ac"},
			{ "moveForward", "be" },
			{ "moveStrafing", "bd" },
			{ "timerSpeed", "d" },
			{ "inventory", "bm" },
			{ "currentItem", "c" },
			{ "getStackInSlot", "a" },
			{ "metadata", "f" },
		};
		break;
	}
	case CASUAL_1_8: {
		g_Mappings = {
			{"net/minecraft/client/Minecraft", "ave"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "bew"},
			{"net/minecraft/client/multiplayer/WorldClient", "bdb"},
			{"net/minecraft/client/gui/GuiScreen", "axu"},
			{"net/minecraft/client/renderer/entity/RenderManager", "biu"},
			{ "net/minecraft/entity/Entity", "pk" },
			{"net/minecraft/client/renderer/entity/Render", "biv"},
			{"net/minecraft/client/model/ModelBase", "bbo"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "auz"},
			{ "net/minecraft/util/IChatComponent", "eu" },
			{"net/minecraft/client/model/ModelRenderer", "bct"},
			{"net/minecraft/util/Timer", "avl"},
			{"net/minecraft/client/gui/Gui", "avp"},
			{"net/minecraft/client/gui/FontRenderer", "avn"},
			{"net/minecraft/util/AxisAlignedBB", "aug"},
			{"net/minecraft/client/gui/GuiChat", "awv"},
			{"net/minecraft/client/renderer/entity/RendererLivingEntity", "bjl"},
			{"net/minecraft/item/ItemStack", "zx"},
			{"net/minecraft/item/ItemSword", "aay"},
			{"net/minecraft/item/ItemAxe", "yl"},
			{"net/minecraft/item/Item", "zw"},
			{ "net/minecraft/item/ItemBlock", "yo" },
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "auh$a"},
			{"net/minecraft/util/MovingObjectPosition", "auh"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "azc"},
			{"net/minecraft/client/gui/GuiChat", "awv"},
			{"net/minecraft/entity/player/InventoryPlayer", "wm"},
			{"net/minecraft/item/ItemEnderPearl", "zk"},
			{ "net/minecraft/block/Block", "afh" },
			{ "net/minecraft/block/state/IBlockState", "alz" },
			{"net/minecraft/util/BlockPos", "cj"},
			{"net/minecraft/client/settings/GameSettings", "avh"},
			{ "net/minecraft/client/settings/KeyBinding", "net/minecraft/client/settings/KeyBinding" },
			{"net/minecraft/block/BlockAir", "aey"},
			{ "keyBindSneak", "field_74311_E" },
			{ "pressed", "field_74513_e" },
			{"gameSettings", "t"},
			{ "getBlockState", "p" },
			{ "getBlock", "c" },
			{ "getIdFromBlock", "a" },
			{"theMinecraft", "S"},
			{"thePlayer", "h"},
			{"theWorld", "f"},
			{"currentScreen", "m"},
			{"getRenderManager", "af"},
			{"getEntityRenderObject", "a"},
			{"mainModel", "f"},
			{"PROJECTION", "c"},
			{"MODELVIEW", "b"},
			{"playerEntities", "j"},
			{ "getDisplayName", "f_" },
			{"getUnformattedTextForChat", "e"},
			{"rotationPitch", "z"},
			{"rotationYaw", "y"},
			{"prevRotationYaw", "A"},
			{"prevRotationPitch", "B"},
			{"posX", "s"},
			{"posY", "t"},
			{"posZ", "u"},
			{"motionX", "v"},
			{"motionY", "w"},
			{"motionZ", "x"},
			{"maxHurtResistantTime", "aD"},
			{"hurtResistantTime", "Z"},
			{"bipedHeadwear", "f"},
			{"bipedRightArm", "h"},
			{"bipedLeftArm", "i"},
			{"bipedRightLeg", "j"},
			{"bipedLeftLeg", "k"},
			{"rotateAngleX","f"},
			{"rotateAngleY","g"},
			{"rotateAngleZ","h"},
			{"prevRenderYawOffset", "aJ"},
			{"renderYawOffset", "aI"},
			{"renderPartialTicks", "c"},
			{"lastTickPosX", "P"},
			{"lastTickPosY", "Q"},
			{"lastTickPosZ", "R"},
			{"timer", "Y"},
			{"displayWidth", "d"},
			{"displayHeight", "e"},
			{ "renderPosX", "o" },
			{ "renderPosY", "p" },
			{ "renderPosZ", "q" },
			{"drawRect", "a"},
			{"getStringWidth", "a"},
			{"drawString", "a"},
			{"fontRendererObj", "k"},
			{ "getHealth", "bn" },
			{"setAlwaysRenderNameTag",  "g"},
			{"isInvisible", "ax"},
			{"maxHurtResistantTime", "aD"},
			{"hurtResistantTime", "Z"},
			{ "viewerPosX", "h" },
			{ "viewerPosY", "i" },
			{ "viewerPosZ", "j" },
			{"boundingBox", "f"},
			{"minX", "a"},
			{"minY", "b"},
			{"minZ", "c"},
			{"maxX", "d"},
			{"maxY", "e"},
			{"maxZ", "f"},
			{"prevPosX", "p"},
			{"prevPosY", "q"},
			{"prevPosZ", "r"},
			{"isSneaking", "av"},
			{"rotationYawHead", "aK"},
			{"onGround", "C"},
			{"getHeldItem", "bA"},
			{"item", "d"},
			{"getItem", "b"},
			{"typeOfHit", "a"},
			{"BLOCK", "b"},
			{"ENTITY", "c"},
			{ "objectMouseOver", "s" },
			{ "inWater", "Y" },
			{ "moveForward", "ba" },
			{ "moveStrafing", "aZ" },
			{ "timerSpeed", "d" },
			{ "inventory", "bi" },
			{ "currentItem", "c" },
			{ "getStackInSlot", "a" },
			{ "metadata", "f" },
		};
		break;
	}
	case FORGE_1_7_10: {
		g_Mappings = {
			{"net/minecraft/client/Minecraft", "net/minecraft/client/Minecraft"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "net/minecraft/client/entity/EntityClientPlayerMP"},
			{"net/minecraft/client/multiplayer/WorldClient", "net/minecraft/client/multiplayer/WorldClient"},
			{"net/minecraft/client/gui/GuiScreen", "net/minecraft/client/gui/GuiScreen"},
			{"net/minecraft/client/renderer/entity/RenderManager", "net/minecraft/client/renderer/entity/RenderManager"},
			{ "net/minecraft/entity/Entity", "net/minecraft/entity/Entity" },
			{"net/minecraft/client/renderer/entity/Render", "net/minecraft/client/renderer/entity/Render"},
			{"net/minecraft/client/model/ModelBase", "net/minecraft/client/model/ModelBase"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "net/minecraft/client/renderer/ActiveRenderInfo"},
			{ "net/minecraft/util/IChatComponent", "net/minecraft/util/IChatComponent" },
			{"net/minecraft/client/model/ModelRenderer", "net/minecraft/client/model/ModelRenderer"},
			{"net/minecraft/util/Timer", "net/minecraft/util/Timer"},
			{"net/minecraft/client/gui/Gui", "net/minecraft/client/gui/Gui"},
			{"net/minecraft/client/gui/FontRenderer", "net/minecraft/client/gui/FontRenderer"},
			{"net/minecraft/util/AxisAlignedBB", "net/minecraft/util/AxisAlignedBB"},
			{"net/minecraft/client/gui/GuiChat", "net/minecraft/client/gui/GuiChat"},
			{"net/minecraft/client/renderer/entity/RendererLivingEntity", "net/minecraft/client/renderer/entity/RendererLivingEntity"},
			{ "net/minecraft/item/ItemStack", "net/minecraft/item/ItemStack" },
			{ "net/minecraft/item/ItemSword", "net/minecraft/item/ItemSword" },
			{ "net/minecraft/item/ItemAxe", "net/minecraft/item/ItemAxe" },
			{ "net/minecraft/item/Item", "net/minecraft/item/Item" },
			{ "net/minecraft/item/ItemBlock", "net/minecraft/item/ItemBlock" },
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "net/minecraft/util/MovingObjectPosition_MovingObjectType"},
			{"net/minecraft/util/MovingObjectPosition", "net/minecraft/util/MovingObjectPosition"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "net/minecraft/client/gui/inventory/GuiInventory"},
			{"net/minecraft/client/gui/GuiChat", "net/minecraft/client/gui/GuiChat"},
			{"net/minecraft/entity/player/InventoryPlayer", "net/minecraft/entity/player/InventoryPlayer"},
			{"net/minecraft/item/ItemEnderPearl", "net/minecraft/item/ItemEnderPearl"},
			{ "net/minecraft/block/Block", "net/minecraft/block/Block" },
			{"net/minecraft/client/settings/GameSettings", "net/minecraft/client/settings/GameSettings"},
			{ "net/minecraft/client/settings/KeyBinding", "net/minecraft/client/settings/KeyBinding" },
			{"net/minecraft/block/BlockAir", "net/minecraft/block/BlockAir"},
			{ "keyBindSneak", "field_74311_E" },
			{ "pressed", "field_74513_e" },
			{"gameSettings", "field_71474_y"},
			{ "getBlock", "func_147439_a" },
			{ "getIdFromBlock", "func_149682_b" },
			{"theMinecraft", "field_71432_P"},
			{"thePlayer", "field_71439_g"},
			{"theWorld", "field_71441_e"},
			{"currentScreen", "field_71462_r"},
			{"renderManagerInstance", "field_78727_a" },
			{"getEntityRenderObject", "func_78713_a"},
			{"mainModel", "field_77045_g"},
			{"PROJECTION", "field_74595_k"},
			{"MODELVIEW", "field_74594_j"},
			{"playerEntities", "field_73010_i"},
			{ "getDisplayName", "func_145748_c_" },
			{ "getUnformattedTextForChat", "func_150261_e" },
			{"rotationPitch", "field_70125_A"},
			{"rotationYaw", "field_70177_z"},
			{"prevRotationYaw", "field_70126_B"},
			{"prevRotationPitch", "field_70127_C"},
			{"posX", "field_70165_t"},
			{"posY", "field_70163_u"},
			{"posZ", "field_70161_v"},
			{"motionX", "field_70159_w"},
			{"motionY", "field_70181_x"},
			{"motionZ", "field_70179_y"},
			{"maxHurtResistantTime", "field_70771_an"},
			{"hurtResistantTime", "field_70172_ad"},
			{"bipedHeadwear", "field_78114_d"},
			{"bipedRightArm", "field_78112_f"},
			{"bipedLeftArm", "field_78113_g"},
			{"bipedRightLeg", "field_78123_h"},
			{"bipedLeftLeg", "field_78124_i"},
			{"rotateAngleX","field_78795_f"},
			{"rotateAngleY","field_78796_g"},
			{"rotateAngleZ","field_78808_h"},
			{"prevRenderYawOffset", "field_70760_ar"},
			{"renderYawOffset", "field_70761_aq"},
			{ "renderPartialTicks", "field_74281_c" },
			{ "lastTickPosX", "field_70142_S" },
			{ "lastTickPosY", "field_70137_T" },
			{ "lastTickPosZ", "field_70136_U" },
			{"timer", "field_71428_T"},
			{ "displayWidth", "field_71443_c" },
			{ "displayHeight", "field_71440_d" },
			{ "renderPosX", "field_78725_b" },
			{ "renderPosY", "field_78726_c" },
			{ "renderPosZ", "field_78723_d" },
			{"drawRect", "func_73734_a"},
			{"getStringWidth", "func_78256_a"},
			{"drawString", "func_85187_a"},
			{"fontRendererObj", "field_71466_p"},
			{ "getHealth", "func_110143_aJ" },
			{"setAlwaysRenderNameTag",  "func_94061_f"},
			{ "isInvisible", "func_82150_aj" },
			{"maxHurtResistantTime", "field_70771_an"},
			{"hurtResistantTime", "field_70172_ad"},
			{ "viewerPosX", "field_78730_l" },
			{ "viewerPosY", "field_78731_m" },
			{ "viewerPosZ", "field_78728_n" },
			{ "boundingBox", "field_70121_D" },
			{ "minX", "field_72340_a" },
			{ "minY", "field_72338_b" },
			{ "minZ", "field_72339_c" },
			{ "maxX", "field_72336_d" },
			{ "maxY", "field_72337_e" },
			{ "maxZ", "field_72334_f" },
			{ "prevPosX", "field_70169_q" },
			{ "prevPosY", "field_70167_r" },
			{ "prevPosZ", "field_70166_s" },
			{"isSneaking", "func_70093_af"},
			{"rotationYawHead", "field_70759_as"},
			{"onGround", "field_70122_E"},
			{ "getHeldItem", "func_70694_bm" },
			{"item", "field_151002_e"},
			{ "getItem", "func_77973_b" },
			{"typeOfHit", "field_72313_a"},
			{"BLOCK", "BLOCK"},
			{"ENTITY", "ENTITY"},
			{ "objectMouseOver", "field_71476_x" },
			{ "inWater", "field_70171_ac" },
			{ "moveForward", "field_70701_bs" },
			{ "moveStrafing", "field_70702_br" },
			{ "timerSpeed", "field_74278_d" },
			{ "inventory", "field_71071_by" },
			{ "currentItem", "field_70461_c" },
			{ "getStackInSlot", "func_70301_a" },
			{ "metadata", "field_77991_e" },
		};
		break;
	}
	case FORGE_1_8: {
		g_Mappings = {
			{"net/minecraft/client/Minecraft", "net/minecraft/client/Minecraft"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "net/minecraft/client/entity/EntityPlayerSP"},
			{"net/minecraft/client/multiplayer/WorldClient", "net/minecraft/client/multiplayer/WorldClient"},
			{"net/minecraft/client/gui/GuiScreen", "net/minecraft/client/gui/GuiScreen"},
			{"net/minecraft/client/renderer/entity/RenderManager", "net/minecraft/client/renderer/entity/RenderManager"},
			{ "net/minecraft/entity/Entity", "net/minecraft/entity/Entity" },
			{"net/minecraft/client/renderer/entity/Render", "net/minecraft/client/renderer/entity/Render"},
			{"net/minecraft/client/model/ModelBase", "net/minecraft/client/model/ModelBase"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "net/minecraft/client/renderer/ActiveRenderInfo"},
			{ "net/minecraft/util/IChatComponent", "net/minecraft/util/IChatComponent" },
			{"net/minecraft/client/model/ModelRenderer", "net/minecraft/client/model/ModelRenderer"},
			{"net/minecraft/util/Timer", "net/minecraft/util/Timer"},
			{"net/minecraft/client/gui/Gui", "net/minecraft/client/gui/Gui"},
			{"net/minecraft/client/gui/FontRenderer", "net/minecraft/client/gui/FontRenderer"},
			{"net/minecraft/util/AxisAlignedBB", "net/minecraft/util/AxisAlignedBB"},
			{"net/minecraft/client/gui/GuiChat", "net/minecraft/client/gui/GuiChat"},
			{"net/minecraft/client/renderer/entity/RendererLivingEntity", "net/minecraft/client/renderer/entity/RendererLivingEntity"},
			{ "net/minecraft/item/ItemStack", "net/minecraft/item/ItemStack" },
			{ "net/minecraft/item/ItemSword", "net/minecraft/item/ItemSword" },
			{ "net/minecraft/item/ItemAxe", "net/minecraft/item/ItemAxe" },
			{ "net/minecraft/item/Item", "net/minecraft/item/Item" },
			{ "net/minecraft/item/ItemBlock", "net/minecraft/item/ItemBlock" },
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "net/minecraft/util/MovingObjectPosition$MovingObjectType"},
			{"net/minecraft/util/MovingObjectPosition", "net/minecraft/util/MovingObjectPosition"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "net/minecraft/client/gui/inventory/GuiInventory"},
			{"net/minecraft/client/gui/GuiChat", "net/minecraft/client/gui/GuiChat"},
			{"net/minecraft/entity/player/InventoryPlayer", "net/minecraft/entity/player/InventoryPlayer"},
			{"net/minecraft/item/ItemEnderPearl", "net/minecraft/item/ItemEnderPearl"},
			{ "net/minecraft/block/Block", "net/minecraft/block/Block" },
			{ "net/minecraft/block/state/IBlockState", "net/minecraft/block/state/IBlockState" },
			{"net/minecraft/util/BlockPos", "net/minecraft/util/BlockPos"},
			{"net/minecraft/client/settings/GameSettings", "net/minecraft/client/settings/GameSettings"},
			{ "net/minecraft/client/settings/KeyBinding", "net/minecraft/client/settings/KeyBinding" },
			{"net/minecraft/block/BlockAir", "net/minecraft/block/BlockAir"},
			{ "keyBindSneak", "field_74311_E" },
			{ "pressed", "field_74513_e" },
			{"gameSettings", "field_71474_y"},
			{ "getBlockState", "func_180495_p" },
			{ "getBlock", "func_177230_c" },
			{ "getIdFromBlock", "func_149682_b" },
			{"theMinecraft", "field_71432_P"},
			{"thePlayer", "field_71439_g"},
			{"theWorld", "field_71441_e"},
			{"currentScreen", "field_71462_r"},
			{"getRenderManager", "func_175598_ae"},
			{"getEntityRenderObject", "func_78713_a"},
			{"mainModel", "field_77045_g"},
			{"PROJECTION", "field_178813_c"},
			{"MODELVIEW", "field_178812_b"},
			{"playerEntities", "field_73010_i"},
			{ "getDisplayName", "func_145748_c_" },
			{"getUnformattedTextForChat", "func_150261_e"},
			{"rotationPitch", "field_70125_A"},
			{"rotationYaw", "field_70177_z"},
			{"prevRotationYaw", "field_70126_B"},
			{"prevRotationPitch", "field_70127_C"},
			{"prevPosX", "field_70169_q"},
			{"prevPosY", "field_70167_r"},
			{"prevPosZ", "field_70166_s"},
			{"motionX", "field_70159_w"},
			{"motionY", "field_70181_x"},
			{"motionZ", "field_70179_y"},
			{"maxHurtResistantTime", "field_70771_an"},
			{"hurtResistantTime", "field_70172_ad"},
			{"bipedHeadwear", "field_178720_f"},
			{"bipedRightArm", "field_178723_h"},
			{"bipedLeftArm", "field_178724_i"},
			{"bipedRightLeg", "field_178721_j"},
			{"bipedLeftLeg", "field_178722_k"},
			{"rotateAngleX","field_78795_f"},
			{"rotateAngleY","field_78796_g"},
			{"rotateAngleZ","field_78808_h"},
			{"prevRenderYawOffset", "field_70760_ar"},
			{"renderYawOffset", "field_70761_aq"},
			{ "renderPartialTicks", "field_74281_c" },
			{"lastTickPosX", "field_70142_S"},
			{"lastTickPosY", "field_70137_T"},
			{"lastTickPosZ", "field_70136_U"},
			{"timer", "field_71428_T"},
			{"displayWidth", "field_71443_c"},
			{"displayHeight", "field_71440_d"},
			{ "renderPosX", "field_78725_b" },
			{ "renderPosY", "field_78726_c" },
			{ "renderPosZ", "field_78723_d" },
			{"drawRect", "func_73734_a"},
			{"getStringWidth", "func_78256_a"},
			{"drawString", "func_175065_a"},
			{"fontRendererObj", "field_71466_p"},
			{ "getHealth", "func_110143_aJ" },
			{"setAlwaysRenderNameTag",  "func_174805_g"},
			{"isInvisible", "func_82150_aj"},
			{"maxHurtResistantTime", "field_70771_an"},
			{"hurtResistantTime", "field_70172_ad"},
			{ "viewerPosX", "field_78730_l" },
			{ "viewerPosY", "field_78731_m" },
			{ "viewerPosZ", "field_78728_n" },
			{"boundingBox", "field_70121_D"},
			{"minX", "field_72340_a"},
			{"minY", "field_72338_b"},
			{"minZ", "field_72339_c"},
			{"maxX", "field_72336_d"},
			{"maxY", "field_72337_e"},
			{"maxZ", "field_72334_f"},
			{"prevPosX", "field_70169_q"},
			{"prevPosY", "field_70167_r"},
			{"prevPosZ", "field_70166_s"},
			{"isSneaking", "func_70093_af"},
			{"rotationYawHead", "field_70759_as"},
			{"onGround", "field_70122_E"},
			{"getHeldItem", "func_70694_bm"},
			{"item", "field_151002_e"},
			{"getItem", "func_77973_b"},
			{"typeOfHit", "field_72313_a"},
			{"BLOCK", "BLOCK"},
			{"ENTITY", "ENTITY"},
			{ "objectMouseOver", "field_71476_x" },
			{ "inWater", "field_70171_ac" },
			{ "moveForward", "field_70701_bs" },
			{ "moveStrafing", "field_70702_br" },
			{ "timerSpeed", "field_74278_d" },
			{ "inventory", "field_71071_by" },
			{ "currentItem", "field_70461_c" },
			{ "getStackInSlot", "func_70301_a" },
			{ "metadata", "field_77991_e" },
		};
		break;
	}
	case FEATHER_1_8: {
		g_Mappings = {
			{"net/minecraft/client/Minecraft", "net/minecraft/client/Minecraft"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "net/minecraft/client/entity/EntityPlayerSP"},
			{"net/minecraft/client/multiplayer/WorldClient", "net/minecraft/client/multiplayer/WorldClient"},
			{"net/minecraft/client/gui/GuiScreen", "net/minecraft/client/gui/GuiScreen"},
			{"net/minecraft/client/renderer/entity/RenderManager", "net/minecraft/client/renderer/entity/RenderManager"},
			{ "net/minecraft/entity/Entity", "net/minecraft/entity/Entity" },
			{"net/minecraft/client/renderer/entity/Render", "net/minecraft/client/renderer/entity/Render"},
			{"net/minecraft/client/model/ModelBase", "net/minecraft/client/model/ModelBase"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "net/minecraft/client/renderer/ActiveRenderInfo"},
			{ "net/minecraft/util/IChatComponent", "net/minecraft/util/IChatComponent" },
			{"net/minecraft/client/model/ModelRenderer", "net/minecraft/client/model/ModelRenderer"},
			{"net/minecraft/util/Timer", "net/minecraft/util/Timer"},
			{"net/minecraft/client/gui/Gui", "net/minecraft/client/gui/Gui"},
			{"net/minecraft/client/gui/FontRenderer", "net/minecraft/client/gui/FontRenderer"},
			{"net/minecraft/util/AxisAlignedBB", "net/minecraft/util/AxisAlignedBB"},
			{"net/minecraft/client/gui/GuiChat", "net/minecraft/client/gui/GuiChat"},
			{"net/minecraft/client/renderer/entity/RendererLivingEntity", "net/minecraft/client/renderer/entity/RendererLivingEntity"},
			{ "net/minecraft/item/ItemStack", "net/minecraft/item/ItemStack" },
			{ "net/minecraft/item/ItemSword", "net/minecraft/item/ItemSword" },
			{ "net/minecraft/item/ItemAxe", "net/minecraft/item/ItemAxe" },
			{ "net/minecraft/item/Item", "net/minecraft/item/Item" },
			{ "net/minecraft/item/ItemBlock", "net/minecraft/item/ItemBlock" },
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "net/minecraft/util/MovingObjectPosition$MovingObjectType"},
			{"net/minecraft/util/MovingObjectPosition", "net/minecraft/util/MovingObjectPosition"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "net/minecraft/client/gui/inventory/GuiInventory"},
			{"net/minecraft/client/gui/GuiChat", "net/minecraft/client/gui/GuiChat"},
			{"net/minecraft/entity/player/InventoryPlayer", "net/minecraft/entity/player/InventoryPlayer"},
			{"net/minecraft/item/ItemEnderPearl", "net/minecraft/item/ItemEnderPearl"},
			{ "net/minecraft/block/Block", "net/minecraft/block/Block" },
			{ "net/minecraft/block/state/IBlockState", "net/minecraft/block/state/IBlockState" },
			{"net/minecraft/util/BlockPos", "net/minecraft/util/BlockPos"},
			{"net/minecraft/client/settings/GameSettings", "net/minecraft/client/settings/GameSettings"},
			{ "net/minecraft/client/settings/KeyBinding", "net/minecraft/client/settings/KeyBinding" },
			{"net/minecraft/block/BlockAir", "net/minecraft/block/BlockAir"},
			{ "keyBindSneak", "field_74311_E" },
			{ "pressed", "field_74513_e" },
			{"gameSettings", "field_71474_y"},
			{ "getBlockState", "func_180495_p" },
			{ "getBlock", "func_177230_c" },
			{ "getIdFromBlock", "func_149682_b" },
			{"theMinecraft", "field_71432_P"},
			{"thePlayer", "field_71439_g"},
			{"theWorld", "field_71441_e"},
			{"currentScreen", "field_71462_r"},
			{"getRenderManager", "func_175598_ae"},
			{"getEntityRenderObject", "func_78713_a"},
			{"mainModel", "field_77045_g"},
			{"PROJECTION", "field_178813_c"},
			{"MODELVIEW", "field_178812_b"},
			{"playerEntities", "field_73010_i"},
			{ "getDisplayName", "func_145748_c_" },
			{"getUnformattedTextForChat", "func_150261_e"},
			{"rotationPitch", "field_70125_A"},
			{"rotationYaw", "field_70177_z"},
			{"prevRotationYaw", "field_70126_B"},
			{"prevRotationPitch", "field_70127_C"},
			{"posX", "field_70165_t"},
			{"posY", "field_70163_u"},
			{"posZ", "field_70161_v"},
			{"motionX", "field_70159_w"},
			{"motionY", "field_70181_x"},
			{"motionZ", "field_70179_y"},
			{"maxHurtResistantTime", "field_70771_an"},
			{"hurtResistantTime", "field_70172_ad"},
			{"bipedHeadwear", "field_178720_f"},
			{"bipedRightArm", "field_178723_h"},
			{"bipedLeftArm", "field_178724_i"},
			{"bipedRightLeg", "field_178721_j"},
			{"bipedLeftLeg", "field_178722_k"},
			{"rotateAngleX","field_78795_f"},
			{"rotateAngleY","field_78796_g"},
			{"rotateAngleZ","field_78808_h"},
			{"prevRenderYawOffset", "field_70760_ar"},
			{"renderYawOffset", "field_70761_aq"},
			{ "renderPartialTicks", "field_74281_c" },
			{"lastTickPosX", "field_70142_S"},
			{"lastTickPosY", "field_70137_T"},
			{"lastTickPosZ", "field_70136_U"},
			{"timer", "field_71428_T"},
			{"displayWidth", "field_71443_c"},
			{"displayHeight", "field_71440_d"},
			{ "renderPosX", "field_78725_b" },
			{ "renderPosY", "field_78726_c" },
			{ "renderPosZ", "field_78723_d" },
			{"drawRect", "func_73734_a"},
			{"getStringWidth", "func_78256_a"},
			{"drawString", "func_175065_a"},
			{"fontRendererObj", "field_71466_p"},
			{ "getHealth", "func_110143_aJ" },
			{"setAlwaysRenderNameTag",  "func_174805_g"},
			{"isInvisible", "func_82150_aj"},
			{"maxHurtResistantTime", "field_70771_an"},
			{"hurtResistantTime", "field_70172_ad"},
			{ "viewerPosX", "field_78730_l" },
			{ "viewerPosY", "field_78731_m" },
			{ "viewerPosZ", "field_78728_n" },
			{"boundingBox", "field_70121_D"},
			{"minX", "field_72340_a"},
			{"minY", "field_72338_b"},
			{"minZ", "field_72339_c"},
			{"maxX", "field_72336_d"},
			{"maxY", "field_72337_e"},
			{"maxZ", "field_72334_f"},
			{"prevPosX", "field_70169_q"},
			{"prevPosY", "field_70167_r"},
			{"prevPosZ", "field_70166_s"},
			{"isSneaking", "func_70093_af"},
			{"rotationYawHead", "field_70759_as"},
			{"onGround", "field_70122_E"},
			{"getHeldItem", "func_70694_bm"},
			{"item", "field_151002_e"},
			{"getItem", "func_77973_b"},
			{"typeOfHit", "field_72313_a"},
			{"BLOCK", "BLOCK"},
			{"ENTITY", "ENTITY"},
			{ "objectMouseOver", "field_71476_x" },
			{ "inWater", "field_70171_ac" },
			{ "moveForward", "field_70701_bs" },
			{ "moveStrafing", "field_70702_br" },
			{ "timerSpeed", "field_74278_d" },
			{ "inventory", "field_71071_by" },
			{ "currentItem", "field_70461_c" },
			{ "getStackInSlot", "func_70301_a" },
			{ "metadata", "field_77991_e" },
		};
		break;
	}
	case LUNAR_1_7_10: {
		g_Mappings = {
			{"net/minecraft/client/Minecraft", "net/minecraft/client/Minecraft"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "net/minecraft/client/entity/EntityClientPlayerMP"},
			{"net/minecraft/client/multiplayer/WorldClient", "net/minecraft/client/multiplayer/WorldClient"},
			{"net/minecraft/client/gui/GuiScreen", "net/minecraft/client/gui/GuiScreen"},
			{"net/minecraft/client/renderer/entity/RenderManager", "net/minecraft/client/renderer/entity/RenderManager"},
			{ "net/minecraft/entity/Entity", "net/minecraft/entity/Entity" },
			{"net/minecraft/client/renderer/entity/Render", "net/minecraft/client/renderer/entity/Render"},
			{"net/minecraft/client/model/ModelBase", "net/minecraft/client/model/ModelBase"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "net/minecraft/client/renderer/ActiveRenderInfo"},
			{ "net/minecraft/util/IChatComponent", "net/minecraft/util/IChatComponent" },
			{"net/minecraft/client/model/ModelRenderer", "net/minecraft/client/model/ModelRenderer"},
			{"net/minecraft/util/Timer", "net/minecraft/util/Timer"},
			{"net/minecraft/client/gui/Gui", "net/minecraft/client/gui/Gui"},
			{"net/minecraft/client/gui/FontRenderer", "net/minecraft/client/gui/FontRenderer"},
			{"net/minecraft/util/AxisAlignedBB", "net/minecraft/util/AxisAlignedBB"},
			{"net/minecraft/client/gui/GuiChat", "net/minecraft/client/gui/GuiChat"},
			{"net/minecraft/client/renderer/entity/RendererLivingEntity", "net/minecraft/client/renderer/entity/RendererLivingEntity"},
			{ "net/minecraft/item/ItemStack", "net/minecraft/item/ItemStack" },
			{ "net/minecraft/item/ItemSword", "net/minecraft/item/ItemSword" },
			{ "net/minecraft/item/ItemAxe", "net/minecraft/item/ItemAxe" },
			{ "net/minecraft/item/Item", "net/minecraft/item/Item" },
			{ "net/minecraft/item/ItemBlock", "net/minecraft/item/ItemBlock" },
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "net/minecraft/util/MovingObjectPosition_MovingObjectType"},
			{"net/minecraft/util/MovingObjectPosition", "net/minecraft/util/MovingObjectPosition"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "net/minecraft/client/gui/inventory/GuiInventory"},
			{"net/minecraft/client/gui/GuiChat", "net/minecraft/client/gui/GuiChat"},
			{"net/minecraft/entity/player/InventoryPlayer", "net/minecraft/entity/player/InventoryPlayer"},
			{"net/minecraft/item/ItemEnderPearl", "net/minecraft/item/ItemEnderPearl"},
			{ "net/minecraft/block/Block", "net/minecraft/block/Block" },
			{"net/minecraft/client/settings/GameSettings", "net/minecraft/client/settings/GameSettings"},
			{ "net/minecraft/client/settings/KeyBinding", "net/minecraft/client/settings/KeyBinding" },
			{"net/minecraft/block/BlockAir", "net/minecraft/block/BlockAir"},
			{ "keyBindSneak", "keyBindSneak" },
			{ "pressed", "pressed" },
			{"gameSettings", "gameSettings"},
			{ "getBlock", "getBlock" },
			{ "getIdFromBlock", "getIdFromBlock" },
			{"theMinecraft", "theMinecraft"},
			{"thePlayer", "thePlayer"},
			{"theWorld", "theWorld"},
			{"currentScreen", "currentScreen"},
			{"renderManagerInstance", "instance" },
			{"getEntityRenderObject", "getEntityRenderObject"},
			{"mainModel", "mainModel"},
			{"PROJECTION", "projection"},
			{"MODELVIEW", "modelview"},
			{"playerEntities", "playerEntities"},
			{ "getDisplayName", "getFormattedCommandSenderName" },
			{"getUnformattedTextForChat", "getUnformattedTextForChat"},
			{"rotationPitch", "rotationPitch"},
			{"rotationYaw", "rotationYaw"},
			{"prevRotationYaw", "prevRotationYaw"},
			{"prevRotationPitch", "prevRotationPitch"},
			{"posX", "posX"},
			{"posY", "posY"},
			{"posZ", "posZ"},
			{"motionX", "motionX"},
			{"motionY", "motionY"},
			{"motionZ", "motionZ"},
			{"maxHurtResistantTime", "maxHurtResistantTime"},
			{"hurtResistantTime", "hurtResistantTime"},
			{"bipedHeadwear", "bipedHeadwear"},
			{"bipedRightArm", "bipedRightArm"},
			{"bipedLeftArm", "bipedLeftArm"},
			{"bipedRightLeg", "bipedRightLeg"},
			{"bipedLeftLeg", "bipedLeftLeg"},
			{"rotateAngleX","rotateAngleX"},
			{"rotateAngleY","rotateAngleY"},
			{"rotateAngleZ","rotateAngleZ"},
			{"prevRenderYawOffset", "prevRenderYawOffset"},
			{"renderYawOffset", "renderYawOffset"},
			{ "renderPartialTicks", "renderPartialTicks" },
			{"lastTickPosX", "lastTickPosX"},
			{"lastTickPosY", "lastTickPosY"},
			{"lastTickPosZ", "lastTickPosZ"},
			{"timer", "timer"},
			{"displayWidth", "displayWidth"},
			{"displayHeight", "displayHeight"},
			{ "renderPosX", "renderPosX" },
			{ "renderPosY", "renderPosY" },
			{ "renderPosZ", "renderPosZ" },
			{"drawRect", "drawRect"},
			{"getStringWidth", "getStringWidth"},
			{"drawString", "drawString"},
			{"fontRendererObj", "fontRendererObj"},
			{ "getHealth", "getHealth" },
			{"setAlwaysRenderNameTag",  "setAlwaysRenderNameTag"},
			{"isInvisible", "isInvisible"},
			{"maxHurtResistantTime", "maxHurtResistantTime"},
			{"hurtResistantTime", "hurtResistantTime"},
			{ "viewerPosX", "viewerPosX" },
			{ "viewerPosY", "viewerPosY" },
			{ "viewerPosZ", "viewerPosZ" },
			{"boundingBox", "boundingBox"},
			{"minX", "minX"},
			{"minY", "minY"},
			{"minZ", "minZ"},
			{"maxX", "maxX"},
			{"maxY", "maxY"},
			{"maxZ", "maxZ"},
			{"prevPosX", "prevPosX"},
			{"prevPosY", "prevPosY"},
			{"prevPosZ", "prevPosZ"},
			{"isSneaking", "isSneaking"},
			{"rotationYawHead", "rotationYawHead"},
			{"onGround", "onGround"},
			{"getHeldItem", "getHeldItem"},
			{"item", "theItem"},
			{"getItem", "getItem"},
			{"typeOfHit", "typeOfHit"},
			{"BLOCK", "BLOCK"},
			{"ENTITY", "ENTITY"},
			{ "objectMouseOver", "objectMouseOver" },
			{ "inWater", "inWater" },
			{ "moveForward", "moveForward" },
			{ "moveStrafing", "moveStrafing" },
			{ "timerSpeed", "timerSpeed" },
			{ "inventory", "inventory" },
			{ "currentItem", "currentItem" },
			{ "getStackInSlot", "getStackInSlot" },
			{ "metadata", "metadata" },
		};
		break;
	}
	case LUNAR_1_8: {
		g_Mappings = {
			{"net/minecraft/client/Minecraft", "net/minecraft/client/Minecraft"},
			{"net/minecraft/client/entity/EntityClientPlayerMP", "net/minecraft/client/entity/EntityPlayerSP"},
			{"net/minecraft/client/multiplayer/WorldClient", "net/minecraft/client/multiplayer/WorldClient"},
			{"net/minecraft/client/gui/GuiScreen", "net/minecraft/client/gui/GuiScreen"},
			{"net/minecraft/client/renderer/entity/RenderManager", "net/minecraft/client/renderer/entity/RenderManager"},
			{ "net/minecraft/entity/Entity", "net/minecraft/entity/Entity" },
			{"net/minecraft/client/renderer/entity/Render", "net/minecraft/client/renderer/entity/Render"},
			{"net/minecraft/client/model/ModelBase", "net/minecraft/client/model/ModelBase"},
			{"net/minecraft/client/renderer/ActiveRenderInfo", "net/minecraft/client/renderer/ActiveRenderInfo"},
			{ "net/minecraft/util/IChatComponent", "net/minecraft/util/IChatComponent" },
			{"net/minecraft/client/model/ModelRenderer", "net/minecraft/client/model/ModelRenderer"},
			{"net/minecraft/util/Timer", "net/minecraft/util/Timer"},
			{"net/minecraft/client/gui/Gui", "net/minecraft/client/gui/Gui"},
			{"net/minecraft/client/gui/FontRenderer", "net/minecraft/client/gui/FontRenderer"},
			{"net/minecraft/util/AxisAlignedBB", "net/minecraft/util/AxisAlignedBB"},
			{"net/minecraft/client/gui/GuiChat", "net/minecraft/client/gui/GuiChat"},
			{"net/minecraft/client/renderer/entity/RendererLivingEntity", "net/minecraft/client/renderer/entity/RendererLivingEntity"},
			{ "net/minecraft/item/ItemStack", "net/minecraft/item/ItemStack" },
			{ "net/minecraft/item/ItemSword", "net/minecraft/item/ItemSword" },
			{ "net/minecraft/item/ItemAxe", "net/minecraft/item/ItemAxe" },
			{ "net/minecraft/item/Item", "net/minecraft/item/Item" },
			{ "net/minecraft/item/ItemBlock", "net/minecraft/item/ItemBlock" },
			{"net/minecraft/util/MovingObjectPosition$MovingObjectType", "net/minecraft/util/MovingObjectPosition$MovingObjectType"},
			{"net/minecraft/util/MovingObjectPosition", "net/minecraft/util/MovingObjectPosition"},
			{"net/minecraft/client/gui/inventory/GuiInventory", "net/minecraft/client/gui/inventory/GuiInventory"},
			{"net/minecraft/client/gui/GuiChat", "net/minecraft/client/gui/GuiChat"},
			{"net/minecraft/entity/player/InventoryPlayer", "net/minecraft/entity/player/InventoryPlayer"},
			{"net/minecraft/item/ItemEnderPearl", "net/minecraft/item/ItemEnderPearl"},
			{ "net/minecraft/block/Block", "net/minecraft/block/Block" },
			{ "net/minecraft/block/state/IBlockState", "net/minecraft/block/state/IBlockState" },
			{ "net/minecraft/util/BlockPos", "net/minecraft/util/BlockPos"},
			{"net/minecraft/client/settings/GameSettings", "net/minecraft/client/settings/GameSettings"},
			{ "net/minecraft/client/settings/KeyBinding", "net/minecraft/client/settings/KeyBinding" },
			{"net/minecraft/block/BlockAir", "net/minecraft/block/BlockAir"},
			{ "keyBindSneak", "keyBindSneak" },
			{ "pressed", "pressed" },
			{"gameSettings", "gameSettings"},
			{ "getBlockState", "getBlockState" },
			{ "getBlock", "getBlock" },
			{ "getIdFromBlock", "getIdFromBlock" },
			{"theMinecraft", "theMinecraft"},
			{"thePlayer", "thePlayer"},
			{"theWorld", "theWorld"},
			{"currentScreen", "currentScreen"},
			{"getRenderManager", "getRenderManager"},
			{"getEntityRenderObject", "getEntityRenderObject"},
			{"mainModel", "mainModel"},
			{"PROJECTION", "PROJECTION"},
			{"MODELVIEW", "MODELVIEW"},
			{"playerEntities", "playerEntities"},
			{"playerEntities", "playerEntities"},
			{ "getDisplayName", "getDisplayName" },
			{"getUnformattedTextForChat", "getUnformattedTextForChat"},
			{"rotationPitch", "rotationPitch"},
			{"rotationYaw", "rotationYaw"},
			{"prevRotationYaw", "prevRotationYaw"},
			{"prevRotationPitch", "prevRotationPitch"},
			{"posX", "posX"},
			{"posY", "posY"},
			{"posZ", "posZ"},
			{"motionX", "motionX"},
			{"motionY", "motionY"},
			{"motionZ", "motionZ"},
			{"maxHurtResistantTime", "maxHurtResistantTime"},
			{"hurtResistantTime", "hurtResistantTime"},
			{"bipedHeadwear", "bipedHeadwear"},
			{"bipedRightArm", "bipedRightArm"},
			{"bipedLeftArm", "bipedLeftArm"},
			{"bipedRightLeg", "bipedRightLeg"},
			{"bipedLeftLeg", "bipedLeftLeg"},
			{"rotateAngleX","rotateAngleX"},
			{"rotateAngleY","rotateAngleY"},
			{"rotateAngleZ","rotateAngleZ"},
			{"prevRenderYawOffset", "prevRenderYawOffset"},
			{"renderYawOffset", "renderYawOffset"},
			{ "renderPartialTicks", "renderPartialTicks" },
			{"lastTickPosX", "lastTickPosX"},
			{"lastTickPosY", "lastTickPosY"},
			{"lastTickPosZ", "lastTickPosZ"},
			{"timer", "timer"},
			{"displayWidth", "displayWidth"},
			{"displayHeight", "displayHeight"},
			{ "renderPosX", "renderPosX" },
			{ "renderPosY", "renderPosY" },
			{ "renderPosZ", "renderPosZ" },
			{"drawRect", "drawRect"},
			{"getStringWidth", "getStringWidth"},
			{"drawString", "drawString"},
			{"fontRendererObj", "fontRendererObj"},
			{ "getHealth", "getHealth" },
			{"setAlwaysRenderNameTag",  "setAlwaysRenderNameTag"},
			{"isInvisible", "isInvisible"},
			{"maxHurtResistantTime", "maxHurtResistantTime"},
			{"hurtResistantTime", "hurtResistantTime"},
			{ "viewerPosX", "viewerPosX" },
			{ "viewerPosY", "viewerPosY" },
			{ "viewerPosZ", "viewerPosZ" },
			{"boundingBox", "boundingBox"},
			{"minX", "minX"},
			{"minY", "minY"},
			{"minZ", "minZ"},
			{"maxX", "maxX"},
			{"maxY", "maxY"},
			{"maxZ", "maxZ"},
			{"prevPosX", "prevPosX"},
			{"prevPosY", "prevPosY"},
			{"prevPosZ", "prevPosZ"},
			{"isSneaking", "isSneaking"},
			{"rotationYawHead", "rotationYawHead"},
			{"onGround", "onGround"},
			{"getHeldItem", "getHeldItem"},
			{"item", "item"},
			{"getItem", "getItem"},
			{"typeOfHit", "typeOfHit"},
			{"BLOCK", "BLOCK"},
			{"ENTITY", "ENTITY"},
			{ "objectMouseOver", "objectMouseOver" },
			{ "inWater", "inWater" },
			{ "moveForward", "moveForward" },
			{ "moveStrafing", "moveStrafing" },
			{ "timerSpeed", "timerSpeed" },
			{ "inventory", "inventory" },
			{ "currentItem", "currentItem" },
			{ "getStackInSlot", "getStackInSlot" },
			{ "metadata", "itemDamage" },
		};
		break;
	}
	default:
		break;
	}
}

/*
	* 1: classic class/field
	* 2: class type
	* 3: method class type
*/
std::string Mapper::Get(const char* mapping, int type)
{
	if (!g_Mappings.count(mapping))
		return std::string("");

	std::string ret;
	switch (type)
	{
	case 1:
		ret = g_Mappings[mapping];
		break;
	case 2:
		ret = "L" + std::string(g_Mappings[mapping]) + ";";
		break;
	case 3:
		ret = "()L" + std::string(g_Mappings[mapping]) + ";";
		break;
	default:
		ret = g_Mappings[mapping];
		break;
	}

	return ret;
}